### ISSUE TITLE
Is the library ready for production environments?

### ISSUE THREAD

**Issue by modesto** [bcuff/MemcachedSharp#1]
I'm looking for async Memcached clients for .Net but it's not an easy task. Ketchup seems to be abandoned and this sounds too "young". Is MemcachedSharp ready for production environments?

Kind regards

**Comment by bcuff** [comment]
It can certainly be used in production. However there are a couple of things you may want to keep in mind -
1. It doesn't do serialization for you. You'll need to read and write to streams using your favorite serialization framework.
2. It doesn't do routing when you have multiple Memcached servers. If you want to do routing you'll need to create a MemcachedClient instance per host.

If you end up using it then I recommend creating a light-weight wrapper around it that addresses these concerns.

Happy coding.
